version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vals_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 3s
      retries: 10

    networks:
      - vals_network

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile

  #   container_name: vals_api
  #   restart: unless-stopped

  #   env_file:
  #     - .env

  #   ports:
  #     - '3000:3000'

  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  #   networks:
  #     - vals_network

  #   stop_grace_period: 30s

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: vals_meilisearch
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:?MEILI_MASTER_KEY is required}
      MEILI_ENV: production
      MEILI_NO_ANALYTICS: 'true'
    ports:
      - '7700:7700'
    volumes:
      - meili_data:/meili_data
    networks:
      - vals_network

volumes:
  postgres_data:
  meili_data:

networks:
  vals_network:
    driver: bridge
