export const SEARCH_INDEX_NAME_CONFIG_KEY = 'MEILI_INDEX';
export const SEARCH_HOST_CONFIG_KEY = 'MEILI_HOST';
export const SEARCH_MASTER_KEY_CONFIG_KEY = 'MEILI_MASTER_KEY';

export const SEARCH_DEFAULT_LIMIT = 10;
export const SEARCH_MAX_LIMIT = 130;
export const SEARCH_MIN_QUERY_LENGTH = 2;
export const SEARCH_MAX_QUERY_LENGTH = 200;
